# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, features/* ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set environmental variable with branch
        run: |
          trimmedBranch=${GITHUB_REF##*/}
          echo "::set-env name=branch::$trimmedBranch"
          perfectBranch="f-"$trimmedBranch
          echo perfectBranch = $perfectBranch
          echo "::set-env name=WORKSPACE::$perfectBranch"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.1.0

      - name: Terraform create WORKSPACE
        if: github.ref == 'refs/heads/features/*' && github.event_name == 'push'
        run: terraform workspace new ${{ env.WORKSPACE }}

      - name: Terraform Validate
        run: terraform validate $SOURCE_DIR/infra/dev/ -no-color

      - name: Terraform Init
        run: terraform init $SOURCE_DIR/infra/dev/

      - name: Terraform plan
        run: terraform plan $SOURCE_DIR