# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, features/* ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set environmental variable with branch
        run: |
          echo Ref = ${GITHUB_REF##*/},
          trimmedBranch=${GITHUB_REF##*}
          echo $trimmedBranch
          perfectBranch=${trimmedBranch/features\//f-}
          echo $perfectBranch
        env:
          WORKSPACE: $perfectBranch

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.1.0

      - name: Terraform create WORKSPACE
        run: terraform workspace new ${GITHUB_REF}

      - name: Terraform Validate
        run: terraform validate $SOURCE_DIR/src/dev/ -no-color

      - name: Terraform Init
        run: terraform init $SOURCE_DIR/src/dev/

      - name: Terraform plan
        run: terraform plan $SOURCE_DIR