# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, features/* ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
        ARM_CLIENT_ID: ${{ secrets.CLIENTID }}
        ARM_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTIONID }}
        ARM_TENANT_ID: ${{ secrets.TENANTID }}
        SOURCE_DIR: ${{ github.workspace }}/infra/dev
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set environmental variable with branch
        run: |
          trimmedBranch=${GITHUB_REF##*/}
          echo "::set-env name=branch::$trimmedBranch"
          perfectBranch="f-"$trimmedBranch
          echo perfectBranch = $perfectBranch
          echo "::set-env name=WORKSPACE::$perfectBranch"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.1.0

      - name: Terraform Init
        run: terraform init $SOURCE_DIR

      - name: Terraform create WORKSPACE
        if: contains('refs/heads/features', github.ref) && github.event_name == 'push'
        run: terraform workspace select ${{ env.WORKSPACE }} -no-color || terraform workspace new ${{ env.WORKSPACE }} -no-color

      - name: Terraform Validate
        run: terraform validate $SOURCE_DIR -no-color

      - name: Terraform Plan
        run: terraform plan $SOURCE_DIR

      - name: Terraform Apply
        run: terraform apply --auto-approve $SOURCE_DIR

      - name: Test and function
        if: github.ref == 'refs/heads/features/*'
        run: |
          curl -GET <ip_address>/health
          terraform destroy 
